# Generated by Django 6.0.2 on 2026-03-17 14:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Color Name')),
            ],
            options={
                'db_table': 'general_color',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Bikini', 'Bikini'), ('Top', 'Top'), ('Falda', 'Falda'), ('Buzo', 'Buzo'), ('Vestido', 'Vestido'), ('Short', 'Short'), ('Set', 'Set'), ('Accesorio', 'Accesorio'), ('Pantalón', 'Pantalón'), ('Camisa', 'Camisa'), ('Otro', 'Otro')], max_length=20, verbose_name='Category')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Price')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock')),
                ('manufacturing_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Manufacturing Time (hours)')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('manufacturing_guide', models.FileField(blank=True, null=True, upload_to='guides/manufacturing/')),
                ('size_guide', models.ImageField(blank=True, null=True, upload_to='guides/sizes/')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ColorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('general_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_colors', to='product.generalcolor', verbose_name='Color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='product.product', verbose_name='Product')),
            ],
            options={
                'db_table': 'product_color',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_image', models.ImageField(upload_to='products/', verbose_name='Image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product', verbose_name='Product')),
            ],
            options={
                'db_table': 'product_image',
            },
        ),
        migrations.CreateModel(
            name='SetProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('set_price', models.DecimalField(decimal_places=2, help_text='Discounted price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Set Price')),
                ('individual_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to_sets', to='product.product', verbose_name='Individual Product')),
                ('set_product', models.ForeignKey(limit_choices_to={'category': 'Set'}, on_delete=django.db.models.deletion.CASCADE, related_name='set_components', to='product.product', verbose_name='Set Product')),
            ],
            options={
                'db_table': 'set_product',
            },
        ),
    ]
