# Generated by Django 6.0.2 on 2026-03-17 14:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, verbose_name='Assigned Date')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Due Date')),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En progreso', 'En progreso'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('color_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='product.colorproduct', verbose_name='Product Color')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='account.user', verbose_name='Employee')),
            ],
            options={
                'db_table': 'production_task',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_supply', models.CharField(choices=[('Hilo', 'Hilo'), ('Botón', 'Botón'), ('Argolla', 'Argolla'), ('Otro', 'Otro')], max_length=20, verbose_name='Type')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('reference', models.CharField(max_length=100, verbose_name='Reference')),
                ('hex_code', models.CharField(blank=True, help_text='Format: #RRGGBB', max_length=7, null=True, verbose_name='HEX Code')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Price')),
                ('general_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplies', to='product.generalcolor', verbose_name='General Color')),
            ],
            options={
                'db_table': 'supply',
            },
        ),
        migrations.CreateModel(
            name='EmployeeInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Quantity')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, verbose_name='Assigned Date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='account.user', verbose_name='Employee')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_inventory', to='production.supply', verbose_name='Supply')),
            ],
            options={
                'db_table': 'employee_inventory',
            },
        ),
        migrations.CreateModel(
            name='SupplyColorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Required Quantity')),
                ('color_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_supplies', to='product.colorproduct', verbose_name='Product Color')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_products', to='production.supply', verbose_name='Supply')),
            ],
            options={
                'db_table': 'supply_color_product',
            },
        ),
        migrations.CreateModel(
            name='TaskSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Delivered Quantity')),
                ('returned_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Returned Quantity')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_supplies', to='production.supply', verbose_name='Supply')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='production.productiontask', verbose_name='Task')),
            ],
            options={
                'db_table': 'task_supply',
            },
        ),
    ]
