# Generated by Django 6.0.2 on 2026-04-23 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_colorproduct_id_alter_generalcolor_id_and_more'),
        ('production', '0003_alter_employeeinventory_id_alter_productiontask_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiontask',
            name='assignment_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de asignación'),
        ),
        migrations.AlterField(
            model_name='productiontask',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='product.colorproduct', verbose_name='Product'),
        ),
    ]
