# Generated by Django 6.0.2 on 2026-03-13 05:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Color Name')),
            ],
            options={
                'db_table': 'general_color',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Order Date')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Discount')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total')),
                ('status', models.CharField(choices=[('Pendiente confirmacion', 'Confirmación de pago pendiente'), ('Confirmado', 'Confirmado'), ('En producción', 'En producción'), ('Completado', 'Completado'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='Pendiente confirmacion', max_length=30, verbose_name='Status')),
                ('customer_note', models.TextField(blank=True, null=True, verbose_name='Customer Note')),
            ],
            options={
                'db_table': 'order',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('instructions', models.TextField(verbose_name='Instructions')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='payment_method/', verbose_name='Payment QR')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'db_table': 'payment_method',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Bikini', 'Bikini'), ('Top', 'Top'), ('Falda', 'Falda'), ('Buzo', 'Buzo'), ('Vestido', 'Vestido'), ('Short', 'Short'), ('Set', 'Set'), ('Accesorio', 'Accesorio'), ('Pantalón', 'Pantalón'), ('Camisa', 'Camisa'), ('Otro', 'Otro')], max_length=20, verbose_name='Category')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Price')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock')),
                ('manufacturing_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Manufacturing Time (hours)')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('manufacturing_guide', models.FileField(blank=True, null=True, upload_to='guias/fabricacion/')),
                ('size_guide', models.ImageField(blank=True, null=True, upload_to='guias/tallas/')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Session Key')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'db_table': 'shopping_cart',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('role', models.CharField(max_length=128, verbose_name='Role')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='ColorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('id_general_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_colors', to='crochet.generalcolor', verbose_name='Color')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='crochet.product', verbose_name='Product')),
            ],
            options={
                'db_table': 'product_color',
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='Payment Receipt')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Amount')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
                ('confirm', models.BooleanField(default=False, verbose_name='Confirmed')),
                ('confirm_date', models.DateTimeField(blank=True, null=True, verbose_name='Confirmation Date')),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='crochet.order', verbose_name='Order')),
                ('id_payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='crochet.paymentmethod', verbose_name='Payment Method')),
            ],
            options={
                'db_table': 'payment_receipt',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], verbose_name='Size')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Unit Price')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal')),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='crochet.order', verbose_name='Order')),
                ('id_product_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='crochet.colorproduct', verbose_name='Color')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='crochet.product', verbose_name='Product')),
            ],
            options={
                'db_table': 'order_detail',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_image', models.ImageField(upload_to='products/', verbose_name='Image')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='crochet.product', verbose_name='Product')),
            ],
            options={
                'db_table': 'product_image',
            },
        ),
        migrations.CreateModel(
            name='SetProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('set_price', models.DecimalField(decimal_places=2, help_text='Discounted price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Set Price')),
                ('id_individual_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to_sets', to='crochet.product', verbose_name='Individual Product')),
                ('id_set_product', models.ForeignKey(limit_choices_to={'category': 'Set'}, on_delete=django.db.models.deletion.CASCADE, related_name='set_components', to='crochet.product', verbose_name='Set Product')),
            ],
            options={
                'db_table': 'set_product',
            },
        ),
        migrations.CreateModel(
            name='ItemCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=3, verbose_name='Size')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Unit Price')),
                ('addition_date', models.DateTimeField(auto_now_add=True, verbose_name='Added At')),
                ('id_product_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='crochet.colorproduct', verbose_name='Color')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='crochet.product', verbose_name='Product')),
                ('id_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crochet.shoppingcart', verbose_name='Cart')),
            ],
            options={
                'db_table': 'cart_item',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_supply', models.CharField(choices=[('Hilo', 'Hilo'), ('Botón', 'Botón'), ('Argolla', 'Argolla'), ('Otro', 'Otro')], verbose_name='Type')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('reference', models.CharField(max_length=100, verbose_name='Reference')),
                ('color', models.CharField(max_length=100, verbose_name='Color')),
                ('hex_code', models.CharField(blank=True, help_text='Format: #RRGGBB', max_length=7, null=True, verbose_name='HEX Code')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Price')),
                ('id_general_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplies', to='crochet.generalcolor', verbose_name='General Color')),
            ],
            options={
                'db_table': 'supply',
            },
        ),
        migrations.CreateModel(
            name='ProductColorSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Required Quantity')),
                ('id_product_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_supplies', to='crochet.colorproduct', verbose_name='Product Color')),
                ('id_supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_products', to='crochet.supply', verbose_name='Supply')),
            ],
            options={
                'db_table': 'product_color_supply',
            },
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='id_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='crochet.user', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crochet.user', verbose_name='Customer'),
        ),
    ]
