# Generated by Django 6.0.2 on 2026-02-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Shirt', 'shirt'), ('pant', 'Pant'), ('skirt', 'Skirt')], default='shirt', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturing_guide',
            field=models.FileField(blank=True, null=True, upload_to='manufacturing_guides/'),
        ),
        migrations.AddField(
            model_name='product',
            name='production_time',
            field=models.PositiveIntegerField(default=3, help_text='Time in days required to produce the product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='size_guide',
            field=models.ImageField(blank=True, null=True, upload_to='size_guides/'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
