# Generated by Django 6.0.2 on 2026-02-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochet', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.CharField(blank=True, default='', help_text='Enter colors separated by commas (e.g., Red, Blue, Green)', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='available_patterns',
            field=models.CharField(blank=True, default='', help_text='Enter patterns separated by commas (e.g., Striped, Solid, Floral)', max_length=200),
        ),
    ]
