# Generated by Django 5.2.4 on 2026-02-15 14:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochet', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Color')),
            ],
            options={
                'db_table': 'color_general',
            },
        ),
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_url', models.CharField(max_length=500, verbose_name='URL del Archivo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('confirmado', models.BooleanField(default=False, verbose_name='Confirmado')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación')),
            ],
            options={
                'db_table': 'comprobante_pago',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('instrucciones', models.TextField(verbose_name='Instrucciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'db_table': 'metodo_pago',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pedido')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal')),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total')),
                ('estado', models.CharField(choices=[('Pendiente pago', 'Confirmación de pago pendiente'), ('Confirmado', 'Confirmado'), ('En producción', 'En producción'), ('Completado', 'Completado'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='Pendiente pago', max_length=30, verbose_name='Estado')),
                ('nota_cliente', models.TextField(blank=True, null=True, verbose_name='Nota del Cliente')),
            ],
            options={
                'db_table': 'pedido',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=10, verbose_name='Talla')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='crochet.pedido', verbose_name='Pedido')),
            ],
            options={
                'db_table': 'pedido_detalle',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Bikini', 'Bikini'), ('Top', 'Top'), ('Falda', 'Falda'), ('Buzo', 'Buzo'), ('Vestido', 'Vestido'), ('Short', 'Short'), ('Set', 'Set'), ('Accesorio', 'Accesorio'), ('Pantalón', 'Pantalón'), ('Camisa', 'Camisa'), ('Otro', 'Otro')], max_length=20, verbose_name='Categoría')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock')),
                ('tiempo_fabricacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiempo de Fabricación (horas)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('guia_fabricacion', models.FileField(blank=True, null=True, upload_to='guias/fabricacion/')),
                ('guia_tallas', models.ImageField(blank=True, null=True, upload_to='guias/tallas/')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='ProductoColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('id_color_general', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_color', to='crochet.colorgeneral', verbose_name='Color')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colores', to='crochet.producto', verbose_name='Producto')),
            ],
            options={
                'db_table': 'producto_color',
            },
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen', models.ImageField(upload_to='productos/', verbose_name='Imagen')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='crochet.producto', verbose_name='Producto')),
            ],
            options={
                'db_table': 'producto_imagen',
            },
        ),
        migrations.CreateModel(
            name='SetProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_set', models.DecimalField(decimal_places=2, help_text='Precio con descuento aplicado', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio en Set')),
                ('id_producto_individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pertenece_a_sets', to='crochet.producto', verbose_name='Producto Individual')),
                ('id_producto_set', models.ForeignKey(limit_choices_to={'categoria': 'Set'}, on_delete=django.db.models.deletion.CASCADE, related_name='componentes_set', to='crochet.producto', verbose_name='Producto Set')),
            ],
            options={
                'db_table': 'set_producto',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='comprobantepago',
            name='id_metodo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='crochet.metodopago', verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='comprobantepago',
            name='id_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobante', to='crochet.pedido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='crochet.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='id_producto_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='crochet.productocolor', verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='crochet.usuario', verbose_name='Cliente'),
        ),
    ]
