# Generated by Django 5.2.4 on 2026-02-15 17:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochet', '0004_colorgeneral_comprobantepago_metodopago_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente confirmacion', 'Confirmación de pago pendiente'), ('Confirmado', 'Confirmado'), ('En producción', 'En producción'), ('Completado', 'Completado'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='Pendiente pago', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pedidodetalle',
            name='talla',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('Única', 'Talla Única')], verbose_name='Talla'),
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Hilo', 'Hilo'), ('Botón', 'Botón'), ('Argolla', 'Argolla'), ('Otro', 'Otro')], verbose_name='Tipo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('referencia', models.CharField(max_length=100, verbose_name='Referencia')),
                ('color', models.CharField(max_length=100, verbose_name='Color')),
                ('codigo_hex', models.CharField(blank=True, help_text='Formato: #RRGGBB', max_length=7, null=True, verbose_name='Código HEX')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio')),
                ('id_color_general', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos', to='crochet.colorgeneral', verbose_name='Color General')),
            ],
            options={
                'db_table': 'insumo',
            },
        ),
        migrations.CreateModel(
            name='ProductoColorInsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_necesaria', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Cantidad Necesaria')),
                ('id_insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_utilizan', to='crochet.insumo', verbose_name='Insumo')),
                ('id_producto_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_necesarios', to='crochet.productocolor', verbose_name='Producto Color')),
            ],
            options={
                'db_table': 'producto_color_insumo',
            },
        ),
    ]
