# Generated by Django 6.0.2 on 2026-02-15 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crochet', '0004_product_available_colors_product_available_patterns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_patterns',
        ),
    ]
