# Generated by Django 6.0.2 on 2026-02-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochet', '0005_remove_product_available_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.CharField(default='White,Black,Blue', help_text='Comma-separated colors (e.g., Red,Blue,Green)', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(default='S,M,L', help_text='Comma-separated sizes (e.g., XS,S,M,L,XL)', max_length=200),
        ),
    ]
