# Generated by Django 6.0.2 on 2026-02-15 22:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochet', '0006_alter_colorgeneral_id_alter_comprobantepago_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Session Key')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to='crochet.usuario', verbose_name='Cliente')),
            ],
            options={
                'db_table': 'carrito_compra',
            },
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=3, verbose_name='Talla')),
                ('cantidad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio Unitario')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Agregado')),
                ('id_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crochet.carritocompra', verbose_name='Carrito')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_carrito', to='crochet.producto', verbose_name='Producto')),
                ('id_producto_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_carrito', to='crochet.productocolor', verbose_name='Color')),
            ],
            options={
                'db_table': 'carrito_item',
            },
        ),
    ]
