# Generated by Django 6.0.2 on 2026-02-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochet', '0007_carritocompra_carritoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodopago',
            name='imagen_qr',
            field=models.ImageField(blank=True, null=True, upload_to='metodo_pago/', verbose_name='QR pago'),
        ),
    ]
