# Generated by Django 6.0.2 on 2026-02-18 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crochet', '0008_metodopago_imagen_qr'),
        ('crochet', '0009_alter_carritocompra_id_alter_carritoitem_id_and_more'),
    ]

    operations = [
    ]
