# Generated by Django 6.0.2 on 2026-02-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochet', '0010_merge_20260218_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobantepago',
            name='archivo_url',
        ),
        migrations.AddField(
            model_name='comprobantepago',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Comprobante de Pago'),
        ),
    ]
