# Generated by Django 6.0.2 on 2026-04-23 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_id'),
        ('order', '0003_alter_financialmovement_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='account.user', verbose_name='Assigned Employee'),
        ),
    ]
