# Generated by Django 6.0.2 on 2026-05-06 15:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_id'),
        ('order', '0004_order_assigned_to'),
        ('production', '0004_alter_productiontask_assignment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmovement',
            name='employee',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'empleada'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_financial_movements', to='account.user', verbose_name='Employee'),
        ),
        migrations.CreateModel(
            name='FinancialMovementSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Quantity')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Unit Cost')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal')),
                ('financial_movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='order.financialmovement')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_movements', to='production.supply')),
            ],
            options={
                'db_table': 'financial_movement_supply',
            },
        ),
    ]
