# Generated by Django 6.0.2 on 2026-05-06 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_financialmovement_employee_financialmovementsupply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialmovementsupply',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='financialmovementsupply',
            name='subtotal',
            field=models.IntegerField(default=0, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='financialmovementsupply',
            name='unit_cost',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unit Cost'),
        ),
    ]
